# Go Dep
# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#version-rules

# Test dependencies
# -----------------------------------------------------------
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/bouk/monkey"
  revision = "5df1f207ff77e025801505ae4d903133a0b4353f"

# General dependencies
# -----------------------------------------------------------
[[constraint]]
  name = "github.com/phR0ze/goquery"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/phR0ze/cast"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.1"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/valyala/bytebufferpool"
  version = "v1.0.0"

# General directives
# -----------------------------------------------------------
[prune]
  non-go = true
  go-tests = true
  unused-packages = true
