# Go Dep
# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#version-rules

# General dependencies
# -----------------------------------------------------------
[[override]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[override]]
  name = "github.com/mitchellh/go-homedir"
  version = "~1.0.0"

# General directives
# -----------------------------------------------------------
[prune]
  non-go = true
  go-tests = true
  #unused-packages = true
